[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["David Choo <7817101+davidchoo12@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
